### ISSUE TITLE
Основной материал вылетает

### ISSUE THREAD

**Issue by Al195** [sergeytolkachyov/WT-Articles-anywhere-with-fields-joomla-content-plugin#1]
Здравствуйте 
{wt_article_wf article_id=XXXX tmpl=XXXX}
article_id=XXXX
проверьте пожалуйста 
если материал из шорт-кода не опубликован
и основной материал вылетает
так и должно быть?
Joomla 3
плагин 1.0.1

**Comment by sergeytolkachyov** [comment]
@Al195 так работает модель компонента материалов, скорее всего. Под тройку уже обновлений точно не будет. Под Joomla 4 / Joomla 5 будет, но попозже. Либо, если есть компетенции - можете тоже подправить, я протестирую и выложу релиз. Об аналогичной проблеме писали в плагине для контактов.

**Comment by sergeytolkachyov** [comment]
@Al195 завтра постараюсь выложить релиз для Joomla 5, где эта ошибка исправлена. Можете даунгрейд сделать для Joomla 3. Хотя лучше обновлять сайт, конечно.

**Comment by sergeytolkachyov** [comment]
Исправлено для Joomla 5.

**Comment by Al195** [comment]
Хорошо, спасибо 👍
